### ISSUE TITLE
Participate in activities

### ISSUE THREAD

**Issue by plexus** [GaiwanTeam/compass#1]
> As a conference attendee, I want to sign up for activities, so that I know I have a guaranteed spot
> As a conference attendee, I want to see how many spots are still available
> As an organizer, I want to see who the participants are

There's currently a "Sign up" button when you expand the activity card, but I would change that caption to "Participate".

This should register this in the database, I think we can make a cardinality/many attribute, `:session/participants`, which are users.

When clicking on "Sign up", we do a `POST /sessions/:id/participate`, this checks if there's still capacity, and if so, adds the person as a participants.

!Caution! there's a risk of race condition here, to do this correctly we'll have to use a dbfn, which is a little annoying because this will complicate deployments a bit (we need to make sure the txor has access to these dbfns). Maybe do the naive thing now without a dbfn, and we'll do that as a separate task.

When the call succeeds we need some visual indication on the card, I was thinking of maybe overlaying a checkmark icon over the activity image, but other ideas are welcome.

Once we have this piece in place, we can hook up the arc which currently just shows a random amount, it's supposed to show how full a activity is (and change color when it gets close to full).

**Comment by humorless** [comment]
From session entity, we have `session/signup`, `session/capacity`, and `session/participants`. 
- how many spots are still available = `(capacity - signup)`
- who the participants are = `participants` (Currently, only Email)
