### ISSUE TITLE
Give people a ticket-holder role in discord if we can verify their tito ticket

### ISSUE THREAD

**Issue by plexus** [GaiwanTeam/compass#13]
Not 100% decided if we do this through the web app or through the discord bot, the main thing is that we don't want to have to manually check for each person if they have a ticket and give them the right role (which will give access to attendee only channels).

We can get tickets/codes/emails from tito, first step might be to see if there's a ticket on the same email, then we can do it immediately. Otherwise, ask people for their booking code, and then flag that ticket as used.

Careful: orders != tickets, an order can have multiple tickets, and the person doing the order might not be the person who the ticket is assigned to.

**Comment by JohnnyJayJay** [comment]
I think it would make sense to put this verification in the web app, this decouples the app from Discord a little. Discord provides a "role connections" API made exactly for the purpose here: you have some Discord-external information that determines whether you get a certain role or not in a server. This is not strictly necessary in our case, we could also simply have the bot add the role when as soon as the verification is done. I've already started looking into these options, I'd definitely help here

**Comment by JohnnyJayJay** [comment]
The backend work for this is mostly done with #17 and #19. What's still needed is a form somewhere on the frontend that asks users for registration reference + email address. The corresponding endpoint on the backend will then verify that there is a valid ticket (via `tito` namespace) and then call the role assignment function (in the `discord` namespace).

**Comment by plexus** [comment]
I tried this out and it seems to work, I'll make a separate ticket for nicer UI integration.
