### ISSUE TITLE
[Bug] Connect with Tito failed

### ISSUE THREAD

**Issue by humorless** [GaiwanTeam/compass#26]
- In production
<img width="1051" alt="截圖 2024-08-27 下午5 48 13" src="https://github.com/user-attachments/assets/db88798c-0a69-424e-8e0c-557aef518e38">

- In local 
<img width="695" alt="截圖 2024-08-27 下午5 48 51" src="https://github.com/user-attachments/assets/083816fd-7484-4487-bbbd-75e99c7d9e61">

**Comment by JohnnyJayJay** [comment]
This could be because the bot can't assign the Orga role due to a lack of permissions
