### ISSUE TITLE
Finish up profile/contact work

### ISSUE THREAD

**Issue by plexus** [GaiwanTeam/compass#40]
## not yet

 - contacts page
   - show private contact information in list
     - show private name if set, othewise public name
     - private bio (markdown)
     - links
   - add export button = EDN dump with all contacts with full profile information (no db/id or uuid)
   
 ## done

- On session/activity pages, hide users that are `:public-profile/hidden?`
  - don't show them in the list
  - at the bottom say "n more", e.g. `and 5 more`
- On the session/activity  -> link to user profile `/user/:uuid`
- Profile page
  - hide edit button unless it's your own profile
  - show public display name
  - show public bio (markdown)
  - show public links
  - if the user is connected (contact), show "contact card"
    - private name
    - private bio
    - private links

**Comment by oxalorg** [comment]
> On session/activity pages, hide users that are :public-profile/hidden?

We also need to show the participant list to non-admin users, it's only visible to admins atm
